#! /bin/sh
SURFPACK=`pwd`; export SURFPACK
PATH="$SURFPACK/../../bin:$PATH"; export PATH 
M4="$SURFPACK/../../bin/m4"; export M4 

aclocal
libtoolize --force --copy
autoheader
automake -a
autoconf
configure -C --prefix=$SURFPACK
