#! /bin/sh
SURFPACK=`pwd`; export SURFPACK
PATH="$SURFPACK/tools/bin:$PATH"; export PATH 
M4="$SURFPACK/tools/bin/m4"; export M4 

aclocal
libtoolize --force --copy
autoheader
automake -a
autoconf
configure -C --prefix=$SURFPACK
