#! /bin/sh
SURFPACK=`pwd`; export SURFPACK
PATH="$SURFPACK/../../bin:$PATH"; export PATH 
M4="$SURFPACK/../../bin/m4"; export M4 
echo executing

SURFPACK=`pwd`; export SURFPACK
# if the tools/ directory doesn't exist, create it
if test ! -d "tools"
then
  echo Making directory tools/
  mkdir tools
fi

cd toolsrc || (echo "Could not cd to toolsrc/" && exit)
echo `pwd`
# Unpack the tar balls.  The toolsrc directory is intended to include the gzipped tarballs for 
# -automake
# -autoconf
# -libtool
# -m4
# -cppunit
# This loop should unpack each tarball, descend into the untarred directory, run configure (with the install location as $SURFPACK/tools), make, and make install.  The .tar archive is then rezippedi, and the unpacked directories are removed.  So the toolsrc directory should be left in the same state it was in at the beginning.

# Traverse each directory, installing the packages in the tools/ directory
echo Installing autotools
preface="[build tools]: "
# Do a reverse sort so that m4 get installed before autoconf 
for i in `ls *.tar.gz | sort -r 2> /dev/null`
do
  gunzip "$i"
  gunzippeddir=`echo $i | sed 's/.gz$//'`
  echo $gunzippeddir
  tar xf "$gunzippeddir"
  echo $preface $gunzippeddir
  gzip "$gunzippeddir"
  untarreddir=`echo $gunzippeddir | sed 's/.tar$//'`
  echo $preface $untarreddir
  if test -d "$untarreddir" 
  then
    echo $preface $untarreddir
    cd "$untarreddir"
    ./configure --prefix="$SURFPACK/../.."
    make
    make install
    cd ..
    rm -rf "$untarreddir"
  fi 
done
echo installed tools

# apply the patch to cppunit.m4
needspatch="$SURFPACK/../../share/aclocal/cppunit.m4"
if test -f "$needspatch"
then
  patch "$needspatch" "$SURFPACK/toolsrc/cppunitpatch"
  echo Applied CPPUnit patch
else
  echo Patch not applied because tools/share/aclocal/cppunit.m4 was not found.
fi 

