#! /bin/sh
rm firstswig.pyc
cp firstswig.py firstswig.py.bak
swig -c++ -python firstswig.i
cp firstswig.py.bak firstswig.py
g++ -c -fpic firstswig.cxx firstswig_wrap.cxx -DHAVE_CONFIG_H -I/usr/include/python2.2 -I/usr/lib/python2.2/config
g++ -shared firstswig.o firstswig_wrap.o -o _firstswig.so
